# config/packages/easy_admin.yaml
easy_admin:
  entities:
    # change the following to the namespaces of your own entities
    - App\Entity\CollectControl
    - App\Entity\Community
    - App\Entity\Pieces
    - App\Entity\StackControl
    - App\Entity\Status
    - App\Entity\User