<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF6LP0SQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF6LP0SQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF6LP0SQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF6LP0SQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerF6LP0SQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'F6LP0SQ',
    'container.build_id' => '45d9f1b8',
    'container.build_time' => 1585129180,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF6LP0SQ');
